name:                pqlparse
version:             0.1.0.0
github:              "kongo2002/pqlparse"
license:             BSD3
author:              "Gregor Uhlenheuer"
maintainer:          "kongo2002@gmail.com"
copyright:           "Gregor Uhlenheuer 2021"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kongo2002/pqlparse#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - text

executables:
  pqlparse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pqlparse
    - containers
    - text

tests:
  pqlparse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pqlparse
    - hspec
    - text
