on:
  - push
name: test and build
jobs:
  build:
    name: test and build (GHC ${{ matrix.ghc }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - '8.6.5'
          - '8.8.4'
          - '8.10.7'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: test
        run: cabal test
      - name: build
        run: cabal build
  stack:
    name: test and build (stack)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup haskell
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
          stack-setup-ghc: true
      - name: test
        run: stack test --coverage
      - name: build
        run: stack build
